name: fireui
description: Fire UI
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.0
  http: ^0.13.5
  platform_device_id: ^1.0.1
  socket_io_client: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter