# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Download flutter package
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build

      - name: Config flutter
        run: flutter config --enable-macos-desktop

      - name: Build
        run: flutter build macos --no-tree-shake-icons --release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Download flutter package
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build

      - name: Config flutter
        run: flutter config --enable-linux-desktop

      - name: Build
        run: flutter build linux --release

      - run: |
          cd build/linux
          ls

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: build/linux/

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Download flutter package
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build

      - name: Config flutter
        run: flutter config --enable-windows-desktop

      - name: Build
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: build/windows/runner/Release

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "windows"
          artifacts: "build/windows/runner/release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Download flutter package
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build

      - name: Build
        run: flutter build apk --no-tree-shake-icons --release

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "android"
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}


  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Download flutter package
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build

      - name: Build
        run: flutter build ios --release --no-codesign
